############################################################
# +------------------------------------------------------+ #
# |                       Заметки                        | #
# +------------------------------------------------------+ #
############################################################
#
#Автор плагина vk.com/tlopster
#
#Любое использование/копирование плагина возможно только
#с разрешения автора
#
############################################################
# +------------------------------------------------------+ #
# |                 Основные Настройки                   | #
# +------------------------------------------------------+ #
############################################################

settings:

  #Включить дополнительное логирование в консоль?
  debug: true

  #Сохранять ли логи плагина в файлы?
  saveLogs: true

############################################################
# +------------------------------------------------------+ #
# |             Настройка функций троллинга              | #
# +------------------------------------------------------+ #
############################################################

trolls:
  kov:
    blockInRegion: true
  launch:
    blockInRegion: true
  push:
    blockInRegion: true
  kartoxa:
    blockInRegion: false
  levitate:
    blockInRegion: true
  boom:
    blockInRegion: true

############################################################
# +------------------------------------------------------+ #
# |                 Сообщения плагина                    | #
# +------------------------------------------------------+ #
############################################################

#Любое сообщение может быть, как списком
#(
#message:
#- '1'
#- '2'
#)
#так и строкой (message: 'String'). Поддерживается формат
#json-сообщений (например, для действий при клике на слово в
#чате).
#json-конструктор для Minecraft: https://www.minecraftjson.com
#Плейсхолдеры из PlaceholderAPI также поддерживаются!

messages:
  usage:
    cwt:
      - ''
      - '&d /cwt reload &f- Перезагрузка конфига'
      - ''
    kov:
      - '&d&l[⚡] &fИспользование: &d/kov (ник)'
    launch:
      - '&d&l[⚡] &fИспользование: &d/launch (ник)'
    push:
      - '&d&l[⚡] &fИспользование: &d/push (ник)'
    kartoxa:
      - '&d&l[⚡] &fИспользование: &d/kartoxa (ник)'
    levitate:
      - '&d&l[⚡] &fИспользование: &d/levitate (ник)'
    boom:
      - '&d&l[⚡] &fИспользование: &d/boom (ник)'

  trollMessages:
    kov:
      sender: '&d&l[⚡] &fВы скинули наковальню на &d%player%&f =D'
      player:
        - '&d&l[⚡] &fИгрок &d%sender% &fскинул на вас &dнаковальню&f!'
        - '&a&l[!] &fЕсли &aвас убило&f - не переживайте, &aваш инвентарь &fсохранён!'
    launch:
      sender: '&d&l[⚡] &fВы отправили &d%player% &fпокорять &dнебеса&f!'
      player:
        - '&d&l[⚡] &fИгрок &d%sender% &fподбросил вас &dпрямо к небу&f!'
        - '&eУии...'
    push:
      sender:
        - '&d&l[⚡] &fВы пнули &d%player%&f!'
        - '&eПрям под ж#опу...'
      player:
        - '&d&l[⚡] &fИгрок &d%sender% &fпнул вас &dпод жо#у&f!'
        - '&eАй, больно же!'
    kartoxa:
      sender:
        - '&d&l[⚡] &fВы закартохили &d%player%&f =D'
        - '&c&l[!] &fУтеряно: &cx%extra_count% шт.&f!'
      player:
        - '&d&l[⚡] &fВас закартохил &d%sender%&f!'
        - '&eКартошки много не бывает!'
    levitate:
      sender:
        - '&d&l[⚡] &fИгрок &d%player% &fподнимается &dв небо &fи скоро &dбудет сброшен&f!'
        - '&eБедный игрок...'
      player:
        - '&d&l[⚡] &fИгрок &d%sender% &fподнимает вас &dв небо&f!'
        - '&eИ скоро сбросит на землю...'
    boom:
      sender:
        - '&d&l[⚡] &fВы взорвали &d%player%&f!'
        - '&eБум!'
      player:
        - '&d&l[⚡] &fВас взорвал &d%sender%&f!'
        - '&eВы чудом выжили...'

  reload: '&aКонфигурация перезагружена!'
  noPermissions: '&cНет прав!'
  playerNotFound: '&c&l[⚡] &fИгрок не найден!'
  cantTrollThisPlayer: '&c&l[⚡] &fВы не можете &cзатроллить &fэтого игрока!'
  playerInRegion: '&c&l[⚡] &fЭтот игрок находится &cв регионе&f!'
  playerInPVP: '&c&l[⚡] &fЭтот игрок сейчас в &cPVP-режиме&f!'
  onlyPlayer: '&cЭту команду может выполнять только игрок!'
