name: CWTroll
version: '1.0'
main: me.tlopster.cwtroll.core.CWPluginMain
api-version: 1.13
author: tlopster
depend:
  - CMI
  - CWRelog
  - WorldEdit
  - WorldGuard
commands:
  cwt:
  kov:
  launch:
  push:
  kartoxa:
  levitate:
  boom:
